# -*- coding: utf-8 -*-
"""RAGpdfChatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ngf-yrkI8F9q_qCD5KxDZ9VqWZvY_Jm-
"""

!pip install -q gradio chromadb pypdf sentence-transformers google-generativeai

import gradio as gr
import chromadb
import google.generativeai as genai
import uuid
import os
from pypdf import PdfReader
from sentence_transformers import SentenceTransformer

# -----------------------------------
# Gemini API
# -------------------------------------
# Set your key as an environment variable instead of hardcoding it.
# In Colab: use the "Secrets" tab (key icon on the left sidebar) to store GEMINI_API_KEY
from google.colab import userdata

genai.configure(api_key=userdata.get('GEMINI_API_KEY'))
llm = genai.GenerativeModel("gemini-2.5-flash")

# ------------------------------------------
# Embedding Model
# -----------------------------------------
print("Loading Embedding Model......")
embedder = SentenceTransformer('all-MiniLM-L6-v2')
print("Embedding Model Loaded!")

# ------------------------------------------
# ChromaDB
# ------------------------------------------
client = chromadb.Client()
collection = client.get_or_create_collection("rag_docs")

# -----------------------------------------
# Chunk Text
# -----------------------------------------
def chunk_text(text, chunk_size=500, overlap=50):
    chunks = []
    start = 0
    while start < len(text):
        end = start + chunk_size
        chunk = text[start:end].strip()
        if chunk:
            chunks.append(chunk)
        start += chunk_size - overlap
    return chunks

# -----------------------------------------
# Extract PDF Text
# -----------------------------------------
def extract_text(pdf):
    reader = PdfReader(pdf.name)
    text = ""
    for page in reader.pages:
        page_text = page.extract_text()
        if page_text:
            text += page_text + "\n"
    return text

# ----------------------------------------
# Upload PDF
# ----------------------------------------
def upload_pdf(pdf):
    global collection

    if pdf is None:
        return "-> Please upload a PDF first."

    text = extract_text(pdf)
    if not text.strip():
        return "-> No extractable text found in this PDF."

    chunks = chunk_text(text)
    print(f"Chunks Created: {len(chunks)}")

    embeddings = embedder.encode(chunks).tolist()

    # Reset collection for new PDF
    try:
        client.delete_collection("rag_docs")
    except Exception:
        pass

    collection = client.get_or_create_collection("rag_docs")

    collection.add(
        documents=chunks,
        embeddings=embeddings,
        ids=[str(uuid.uuid4()) for _ in chunks]
    )

    return f"-> PDF Indexed Successfully ({len(chunks)} chunks)"

# --------------------------------------
# Ask Question
# --------------------------------------
def ask(question):
    if not question or not question.strip():
        return "Please enter a question."

    if collection.count() == 0:
        return "Please upload and index a PDF first."

    query_embedding = embedder.encode(question).tolist()

    result = collection.query(
        query_embeddings=[query_embedding],
        n_results=3
    )

    context = "\n".join(result["documents"][0])
    context = context[:4000]  # prevent timeout

    prompt = f"""
    Answer ONLY using the context below.
    If the answer is not found, say:
    'I couldn't find the answer in the document.'

    Context:
    {context}

    Question:
    {question}
    """

    response = llm.generate_content(prompt)
    return response.text

# -------------------------------
# Gradio Interface (Bright Theme)
# -------------------------------

custom_css = """
.gradio-container {
    background: linear-gradient(135deg, #FFE29F, #FFA99F, #FF719A);
}
#title_md h1 {
    color: #FFFFFF !important;
    text-shadow: 1px 1px 3px rgba(0,0,0,0.3);
}
.gr-button {
    background: #FF6B6B !important;
    color: white !important;
    border-radius: 10px !important;
    font-weight: bold !important;
}
.gr-button:hover {
    background: #FF3B3B !important;
}
"""

theme = gr.themes.Soft(
    primary_hue="pink",
    secondary_hue="yellow",
    neutral_hue="slate"
)

with gr.Blocks(theme=theme, css=custom_css) as demo:
    gr.Markdown("# 📄 RAG PDF Chatbot", elem_id="title_md")

    pdf = gr.File(label="Upload PDF")
    upload_btn = gr.Button("Index PDF", variant="primary")
    status = gr.Textbox(label="Status")

    upload_btn.click(upload_pdf, inputs=pdf, outputs=status)

    question = gr.Textbox(label="Ask a Question")
    ask_btn = gr.Button("Ask", variant="primary")
    answer = gr.Textbox(label="Answer", lines=10)

    ask_btn.click(ask, inputs=question, outputs=answer)

demo.launch(debug=True)